CREATE TABLE users (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  first_name VARCHAR(50) NOT NULL,
  last_name VARCHAR(50) NOT NULL,
  email VARCHAR(250) NOT NULL,
  password VARCHAR(100) NOT NULL,
  created_at timestamp DEFAULT current_timestamp,
  updated_at timestamp DEFAULT current_timestamp
);

CREATE OR REPLACE FUNCTION trigger_set_updated()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_updated
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE PROCEDURE trigger_set_updated();

CREATE TYPE error_level AS ENUM ('debug', 'info', 'warning', 'error', 'fatal');

CREATE TABLE errors (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  hash VARCHAR(100) NOT NULL,
  message TEXT NOT NULL,
  details TEXT NOT NULL,
  level error_level NOT NULL,
  origin VARCHAR(100) NOT NULL,
  reported_by INTEGER NOT NULL,
  created_at timestamp DEFAULT current_timestamp,
  FOREIGN KEY (reported_by) REFERENCES users (id)
);

CREATE INDEX idx_errors ON errors (hash, message);
